# Generated by Django 5.2.6 on 2025-09-18 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_auto_20250913_0051"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteAuthConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_email_signup",
                    models.BooleanField(
                        default=True,
                        help_text="Allow users to sign up with email/password",
                    ),
                ),
                (
                    "allow_social_login",
                    models.BooleanField(
                        default=True,
                        help_text="Allow social authentication (Google, GitHub, etc.)",
                    ),
                ),
                (
                    "primary_provider",
                    models.CharField(
                        choices=[
                            ("email", "Email/Password"),
                            ("google", "Google OAuth"),
                            ("github", "GitHub OAuth"),
                            ("microsoft", "Microsoft OAuth"),
                            ("openid_connect", "OpenID Connect"),
                        ],
                        default="email",
                        help_text="Primary authentication method for this tenant",
                        max_length=50,
                    ),
                ),
                (
                    "custom_oauth_settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom OAuth provider settings specific to this tenant",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auth_config",
                        to="core.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Authentication Configuration",
                "verbose_name_plural": "Site Authentication Configurations",
            },
        ),
    ]
